### ISSUE TITLE
Change Job Run human state name

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/pre-assembly#1316]
The current human state name for a Job Run appends "(with preassembly errors)" if there were errors during preassembly (either a preassembly or a discovery job). They are labeled as "preassembly" errors to distinguish them from errors that might occur during accessioning.

Thus, human labels might include:
* Preassembly complete (with preassembly errors)
* Discovery report complete (with preassembly errors)
* Accessioning complete (with preassembly errors)

Is this the correct human names? If not, what should be?

**Comment by andrewjbtw** [comment]
The states bring me back to my thought from an earlier standup that for Preassembly jobs we should stop saying "Preassembly" or "Accessioning" and instead just say "Job." Ultimately, it's the job that gets completed even if accessioning hits an error and a druid isn't accessioned.

We also should report "with accessioning errors".

That would give us:

- Job complete (with accessioning errors)
- Job complete (with Preassembly errors)

Discovery reports are self-contained. Ideally, discovery reports would have a simple status and not say "with discovery errors" since that's redundant:

- Discovery report complete (with errors)

**Comment by justinlittman** [comment]
@andrewjbtw What if there are accessioning and preassembly errors?

**Comment by andrewjbtw** [comment]
We should report both categories if both types of error happened.

Job complete (with Preassembly and accessioning errors).

**Comment by justinlittman** [comment]
@andrewjbtw I realized I'm still confused. What would the status for the following be (ignoring errors):
* preassembly job not completed
* preassembly job completed but accessioning is not complete
* preassembly job completed and accessioning is complete

**Comment by andrewjbtw** [comment]
I thought we currently have those as

- preassembly job not completed: "Running"
- preassembly job completed but accessioning is not complete: "Preassembly completed"
- preassembly job completed and accessioning is complete: "Accessioning completed"

**Comment by justinlittman** [comment]
In https://github.com/sul-dlss/pre-assembly/issues/1316#issuecomment-1740058937 you suggested changing "Preassembly" to "Job". Do you still want to do that?

**Comment by andrewjbtw** [comment]
I'm having my own difficulties keeping track of state. Instead of what I wrote above, let's do this

- preassembly job not completed: "Running"
- preassembly job completed but accessioning is not complete: "Running"
- preassembly job completed and accessioning is complete: "Job completed"

**Comment by justinlittman** [comment]
Will do.
