### ISSUE TITLE
what ActiveRecord models do we need?

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/pre-assembly#141]
For the UI history controller, need to know what Models we need to support the job history and job submission.

**Comment by jmartin-sul** [comment]
my guess without having thought much about it yet is that we'll want at least:
* a model for the user
* a model for a pre-assembly job execution
* a model for a discovery report job execution

the latter two w/ non-null FK back to the user table/model.  or maybe the job history is all in one table, with a type enum?  dunno, we can discuss in the data modelling meeting @SaravShah just scheduled.

**Comment by jmartin-sul** [comment]
turned this into a general ticket for our first pass at the data model

**Comment by jmartin-sul** [comment]
User model:  sunet id.  prob don't need anything else?  can send email based on sunet, just need a rails session, if they can reach the app they're authed, because it's behind webauth for a single workgroup.

**Comment by jmartin-sul** [comment]
options model:
* FK back to user that submitted it
* `label`?  user entered.  something a user can skim for in their history.
*  `options_hash`, or `options_json`

actually, just turn `BundleContext` into an ActiveRecord model.  come up with a better name later if there's time.

**Comment by jmartin-sul** [comment]
job history models (`PreAssemblyRun`, `DiscoveryReportRun`):
* FK back to a `BundleContext` instance
* results don't get stored in the DB, maybe we point to result location, but we think it's deterministic based on bundle dir anyway.

would be nice to go to a set of params in history (a `BundleContext` instance), and re-run pre-assembly or discovery based on that, so that user doesn't have to re-enter params for every run.  @blalbrit says this is a nice to have, but can live w/ users re-entering every time.

reports must be persisted for long enough for the user to retrieve the results.

fine for discovery report to be written to subdir of the user's bundle dir.

currently shares that we're using are mounted read only, that'd have to change.

this comment should spawn some tickets outside the scope of this original ticket.

could also serve the output file from the webserver.

**Comment by jmartin-sul** [comment]
models in aggregate, active record and otherwise
* `User` (to-be-written AR model)
* `BundleContext` (will become AR model)
  * has a controller that takes options from user
* `PreAssemblyRun` (to-be-written AR model) - has output or not, shows up in history
  * if we did put results in DB, it'd go on this table, but for now, pointer to output location if it's not completely deterministic, which it might be.
* `DiscoveryReportRun` (to-be-written AR model) - has output or not, shows up in history
  * if we did put results in DB, it'd go on this table, but for now, pointer to output location if it's not completely deterministic, which it might be.
* `PreAssemblyJob`
* `DiscoveryReportJob`

**Comment by jmartin-sul** [comment]
controllers:  
* submit a job
* show the history

**Comment by jmartin-sul** [comment]
some tickets:
create a user model
turn bundle context into an AR model
job history model/models

**Comment by jmartin-sul** [comment]
will clean up the above comments and ticket stuff after lunch

**Comment by jmartin-sul** [comment]
all relevant info has been captured in other tickets which are being worked on, closing this one
