### ISSUE TITLE
job history ActiveRecord models

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#175]
first question, is this one model for the history in general, or a model for pre-assembly run history, and a separate model for discovery report run history?

once that's answered, create the model or modles.  see https://github.com/sul-dlss/pre-assembly/issues/141#issuecomment-417424792:

> job history model or models (`PreAssemblyRun` and `DiscoveryReportRun`, or just `JobRun` with a Rails enum for the job type, if it's just one table):
> * FK back to the `BundleContext` instance that provided the params for the job execution
> * results don't get stored in the DB.  maybe we point to result location on the file system, but we think it's deterministic based on bundle dir anyway, so probably not necessary?

**Comment by atz** [comment]
I think we can use the same output model for both kinds of job since the inputs are essentially the same.  

If we are using a filesystem output, we should definitely keep a pointer (the filepath) to the output in the output model.  This would be the signifier that the job completed, which is important to any presentation of an "index" of jobs.  (You don't want to have to check the filesystem 100 times to present a list of w 100 jobs showing whether they are complete or not.  Also, just because the file has started to be written does NOT mean it is complete, so that would be a faulty indicator anyway.)

Arguably, this model should be a "JobExecutionWrapper", since it would make sense to pass it as the param (rather than a BundleContext itself) to either job.  It references both input (via FK) and output (via filepath).
