### ISSUE TITLE
add honeybadger.yml to shared_configs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#184]
- [ ] for stage
- [ ] for prod 
- for dev ... do we want to do something in the code somewhere so we don't get:

```
2.4.4 (main):0 Pry > b.run_pre_assembly
2018-09-04 13:58:29 -0700: Pre-assembly started for Revs
2018-09-04 13:58:29 -0700: 3 objects to pre-assemble
2018-09-04 13:58:29 -0700: 3 total objects found, 0 already completed objects skipped
2018-09-04 13:58:29 -0700: 3 remaining in run | 3 running | ~ remaining: 
Working on 'spec/test_data/bundle_input_a/image1.tif' containing 1 files
** [Honeybadger] Unable to send error report: API key is missing. id=6bd43096-552c-418c-a53c-b8a267c8dda9 level=3 pid=1430
```

**Comment by atz** [comment]
https://github.com/sul-dlss/shared_configs/pull/699
https://github.com/sul-dlss/shared_configs/pull/698

In development, you can just put a real or fake `api_key`.  By default, Honeybadger doesn't report during development.  Of course, this app does 3 manual calls to `Honeybadger.notify`, so that is sorta weird.  One will be unused and the 2 in `Bundle` are bogus.  They notify, then raise.  Not much point to that, since they could just `raise` and Honeybadger would get the notification anyway.
