### ISSUE TITLE
make test fixtures valid where they should be

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/pre-assembly#218]
reduced scope of options have rendered some of the configs for our test fixtures invalid (see #207).

for configs for test cases where we don't intend to test an invalid config, we should make the conform to our current expectations.

**Comment by atz** [comment]
More to the point, it is likely many of the fixtures can be collapsed.  To the extent they were created to be "same_as_other_fixture_but_x_is_false", when we remove X, we get rid of the need for a separate fixture.  

We can also get away from using YAML as the reference-point and basically start from a params hash.

W/ OO classes we can also use mocking to much greater effect.  Instead of a whole separate YAML file, just use the same fixture with `allow(obj).to receive(:x).and_return(false)`.  Way more clear about test intent than having to pull up a YAML file.

**Comment by ndushay** [comment]
I'm calling this done
