### ISSUE TITLE
use dor-services-app to check for registered objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#226]
the discovery report uses the dor-services gem to look up objects in DOR;  this could be switched to use the dor-services-app (if not as is, then the dor-services-app should have this functionality added)

app/services/discovery_report.rb - `registration_check`

**Comment by atz** [comment]
In dor-services-app, it is *almost* sufficient for our purposes to implement servicing a `HEAD` request for a URL corresponding to a druid.  (Basically, `exists?` or `404`.)

However, we also need to connect the druid to its APO and check for that.  So that would require returning some kind of body (a `GET`) and parsing it for a follow-up request, or using some kind of object model (like `dor-services).  

Alternatively, we could setup d-s-a to internalize the APO check part, too (for a given route).

**Comment by ndushay** [comment]
See PR #615;  we wouldn't have had to deal with that if we were using dor-services-client.  :-)

**Comment by ndushay** [comment]
also:  consider if lyberservices-scripts needs a super similar fix (if it hasn't been retired yet)
