### ISSUE TITLE
Update SMPL's pre-assembly script to support image thumbs in media objects

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/pre-assembly#26]
SMPL uses a script to generate a manifest about content to be accessioned. In order to take advantage of new image thumb functionality for media objects, the script should be updated.

Link to documentation about the script is here: https://consul.stanford.edu/pages/viewpage.action?pageId=136365158#AutomatedAccessioningandObjectRemediation(pre-assemblyandassembly)-SMPLContent

See https://github.com/sul-dlss/pre-assembly/blob/ea3c4e5580fbdc773eff2a272a4aa85d5924e391/lib/pre_assembly/smpl_precontent_metadata.rb

pair with peter

**Comment by LynnMcRae** [comment]
Here is an email thread with Geoff that may reveal relevant particulars...

A couple of preliminary thoughts for pairing images with individual files/resources:

1. Yes, if the sequence number tells us the members of one resource, then you would simply add a final Sequence 1 row for a jp2. 

2. The name “file-level thumb” is potentially misleading, because we’re talking only about an image icon associated with just the one resource, not acting as a “thumb" to the object as a whole.  The presence of the jp2 inside the same resource is sufficient for this objective. No “thumb” column needed.

3. Now, if we switch to talking about the thumbnail for the object as a whole, the rules are to look first for a resource that has thumb=yes added, else find the first thumb or image resource.  That would mean your augmented manifest:

filename				label				sequence
vc018zp5925_pm.mov	Tape 1				1
vc018zp5925_sh.mpeg	Tape 1				1
vc018zp5925_pm.mp4	Tape 1				1
vc018zp5925_pm.jp2	Tape 1				1
vc018zp5925_img_1.tif	Image of media (1 of 2)	2
vc018zp5925_img_2.tif	Image of media (2 of 2)	3

would use the new jp2 as an image icon inside embed for the video, but still use the jp2 derived from vc018zp5925_img_1.tif as the object thumb, unless you explicitly marked the new jp2 or the second tif to be used instead via a new “thumb” column (that would need to be coded for).

I hope this is more illuminating than confusing!

Lynn


On Aug 24, 2016, at 4:56 PM, Geoffrey C. Willard <gwillard@stanford.edu> wrote:

In preparation for this meeting, and in thinking about the thumbnail issue, it occurred to me that Peter’s SMPL content metadata generation script will likely need to be updated: 

https://consul.stanford.edu/pages/viewpage.action?pageId=136365158

When pairing thumbnails with individual files, I’m not 100% sure how I should go about constructing the smpl_manifest.csv (example attached). Lynn, based on the ‘The Rules of Thumb’ page, it looks like I should add in the thumbnail file (i.e. vc018zp5925_thumb.jp2) with the Tape 1 resource (maintaining the same label), and then add in a column called ‘thumb’ and set the value for that row to yes. Presumably preserve, publish, and shelve should all be set to yes for the thumb as well?

- Geoff

**Comment by LynnMcRae** [comment]
bottom line, it doesn't appear any changes are needed for Geoff to simply include a jp2 file row along with other files sharing a Sequence number (inside the same resource), unless of course assembly would ignore it for some reason.  But if smpl is interested in the ability to designate an **object** thumb other than the default "first-image" rule, it would require I think the suggested extra "thumb" column to mark the image they want to use as object-level thumb..

**Comment by peetucket** [comment]
we could provide support for an extra thumb column in the manifest, if found and set to true, it could generate a separate resource with just the file in that row (presumably a JP2) with specific attributes ... note that the resource type for any row should be already specifiable in a separate column in the manifest called "resource_type"

**Comment by LynnMcRae** [comment]
no need to generate a separate resource. it just means adding attribute `thumb="yes"` to the \<resource> it is marked in.
