### ISSUE TITLE
accession_items is set to nil and will not be supported

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/pre-assembly#262]
This means that the `only` and `except` parameters will be defunct and can go through the code to remove

**Comment by jmartin-sul** [comment]
if we want to support this in the command-line app in the future, we should prob keep this functionality around, even if it's dormant/inaccessible from the web app config.  if it turns out we don't want this at all, we can excise it entirely.  but it did get cleaned up to become slightly more readable, and it'd be easy enough to leave in.

if we did keep it around, we'll prob want to unbreak and read this test:
https://github.com/sul-dlss/pre-assembly/blob/8d6c27da4add227a98ff70edfaa0e468b01cdda1/spec/lib/pre_assembly/bundle_spec.rb#L208-L237

**Comment by ndushay** [comment]
Just spoke with @jmartin-sul  and it's not a bad idea to remove @accession_items from the rails app code at this point.  If we need to add this functionality back in, it may be far enough in the future that the legacy branch might differ even more than it does now.  My main suggestion is to make a single commit removing it, with a clear commit message, so if we need it back, we can easily see it.
