### ISSUE TITLE
stageable_discovery in batch_context.rb

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/pre-assembly#274]
- provide default values for `def stageable_discovery`, these will be hardcoded for the web-app:

```
Use_container: false
Open container folder, well what in the folder do I actually need to stage
glob
Hard coded to **/*
Regex is nil
Files_only always true
```

**Comment by ndushay** [comment]
smpl may use stageable_discovery

![image](https://user-images.githubusercontent.com/96775/45717569-391fdc80-bb4f-11e8-9fb7-db16a5fddb1d.png)

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/45718408-bf3d2280-bb51-11e8-9e84-fe6c477f1e2a.png)

![image](https://user-images.githubusercontent.com/96775/45718415-c6fcc700-bb51-11e8-8474-353f349d8c8e.png)

orig code:
![image](https://user-images.githubusercontent.com/96775/45718499-0cb98f80-bb52-11e8-8e0b-4abf75c33ac8.png)

that was changed possibly here?  #207

**Comment by jmartin-sul** [comment]
example of `stageable_discovery` configuration from legacy branch:
https://github.com/sul-dlss/pre-assembly/blob/f3f947e21aa5c76e2b963a0ed45f32c3d2269b3e/config/projects/TEMPLATE.yaml#L148-L208

**Comment by jmartin-sul** [comment]
@blalbrit, it seems very unlikely that we'll get to re-implementing `stageable_discovery` configuration in this work cycle.  but is it a desirable feature to resurrect in the future?  or is there no longer a use for it?

since it wasn't necessary for this pass at the web app, we allowed ourselves to make a lot of simplifications in our refactoring, by assuming the default value.  but there are still some vestiges of the old ability to configure it, and ideally we'd like to make it work and test it, or remove it totally.  the remaining cruft references this ticket.

**Comment by blalbrit** [comment]
@jmartin-sul - let's leave the possibility open until we know a bit more about any gaps exposed by users. My hope would be that we can continue on the simplifying trend.

**Comment by ndushay** [comment]
@andrewjbtw  says:  

> I’d still like to figure out what’s desirable to port over [from lyberservices-scripts functionality]. I keep learning that Ben uses things from there that no one else knows how to use.
> I could be out of date on the readmes, but at the end of the last maintenance work cycle it looked like the pre-assembly readme still had text about methods not in the UI
