### ISSUE TITLE
User model needs way to get sunetid OR full email?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#309]
We want to be able to get the full email in some contexts, and just the sunetid (for output dirs, for example)

Maybe it's as simple as a convenience method in User model to get part of email before "@" character.  

While doing this, maybe rename the field from "sunetid" to "email" ???

**Comment by ndushay** [comment]
For now, we're just going with output dir having full email

**Comment by atz** [comment]
My understanding is that a `sunet_id` is the username portion of an email.  

Totally fine with an `User#email` convenience method, but it doesn't make sense to have a `sunet_id` with full email address values stored in it.  Also seems preferable to have sunet_id be the component in the directory structure, since `@` and `.` are special characters to the filesystem.

**Comment by ndushay** [comment]
it has been empirically shown that an email address can be a directory name, both on mac os and on our VMs.

**Comment by peetucket** [comment]
I added an `.email` convenience method on the user model in #302 that we can alter later when/if we split sunet_id from email

**Comment by jmartin-sul** [comment]
FWIW, webauth/shib give us the full email address as `sunetid`.  i'm not sure whether the full email address _is_ now considered the sunetid:  i've heard that one of the advantages of shib vs our old webauth system is inter-institution interoperability.  so maybe the domain name is a necessary qualifier?  not sure.

**Comment by atz** [comment]
It is allowed (like whitespace or other special chars), but must be escaped.

**Comment by atz** [comment]
I'm closing this since we provide an `email` method that should be used by consumers who want a guaranteed email address.  Right now, we don't have any consumers looking for just the sunet_id, so we can deal with that if/when the need arises.  

Separately we can undertake to migrate the model attribute to be called `email` since that is what we are storing, but for now the usage pattern is established.
