### ISSUE TITLE
BC controller:  when save fails, better error page to user

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#310]
When the app fails, it gives the generic rails error page, which isn't a good user experience.  Moreover, developer needs to troll through rails logs to find out what error was thrown and any messages.

It would be better if we gave a better error page to the user, complete with error information and what the end_user should DO (like, send an email to some list, or call Donald Trump or something)

**Comment by atz** [comment]
It is pretty conventional to render the "new" template again (i.e. where they were coming from) with the object-that-has-errors.  That way it has their old values and they get another shot at modifying them (ideally prompted by a friendly error message).

**Comment by atz** [comment]
Probably that `validate_xxx` method should do the same thing as the rest of them and just add to `errors` instead of raising.  Also, it should be split up (as previously proposed).  

You're missing that the `new` form *usually* gets an empty new object, but can also get the yet-unsaved validation-failing object-with-errors.  That is to say, the form can be pre-populated with the previous values.  That's normal.  `simple_form` will know what to do.
