### ISSUE TITLE
The CLI should not be marked as "deprecated"

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/pre-assembly#437]
@blalbrit indicated that the CLI is still useful and necessary.  We should update the documentation so that we aren't calling it deprecated.

**Comment by jmartin-sul** [comment]
my understanding is that we ultimately want to retire the v3-legacy branch, and that eventually we'll try to move any functionality we want in the long term to master (preferably to its web app interface).  in that sense, CLI on v3-legacy seems deprecated by my understanding of the term, since we want to urge users toward the newer web app, and away from the the CLI on the legacy branch.

though i agree that in practice, CLI on v3-legacy might effectively stick around forever, and @blalbrit and @peetucket are its only users IIRC, so i can see how the current description could be confusing.

or maybe i was misunderstanding entirely and there's no intention even in principle to fold the v3-legacy CLI functionality into master?

**Comment by jcoyne** [comment]
I would hope that we could fold all the required functionality into one branch at the very least.   To deprecate something, to me means, there is something else that you should use, but @blalbrit is telling us there is nothing else that would replace the functionality of the CLI.

**Comment by jmartin-sul** [comment]
yeah, good point about there being no replacement.  i guess that makes deprecated more aspirational than real, so i retract my objection.
