### ISSUE TITLE
Generalize the media_manifest.csv accessioning method to apply to all content types

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/pre-assembly#751]
For most content types, pre-assembly users have very limited access to contentMetadata settings. For the media content type, users supply a "media_manifest.csv" that enables them to configure:

- resource types
- resource groupings
- resource labels
- file-level publish, preserve, and shelve settings

Users have an ongoing need to access these settings for other content types. This will enable:

- editing data that previously could only be edited in the contentMetadata XML
- displaying captions on images (instead of "Image 1", etc.)
- enabling accessioning of OCR'd documents
- better support for the bundles of files that make up 3D objects (which need different publish/shelve than defaults)
- accessioning of born-digital file types where defaults do the wrong thing

To implement this we should:
- [x] Enable the media_manifest.csv as an option (not required) for all content types
  - [x] Rename the manifest so the name doesn't have "media" in it 
- [x] Update the UI so users can indicate if they are submitting a manifest 
- [x] Decouple the manifest from relying on the druid being in the filename. The current implementation requires a druid in each file name.
- [x] Add file role to the manifest options. This is needed to support OCR.
- [x] Remove special filename conventions from SMPL that drive publish/preserve/shelve?
- [x] Remove source_id column
- [ ] Update documentation
  - [ ] new page here: https://github.com/sul-dlss/pre-assembly/wiki/Accessioning-complex-content
  - [ ] https://consul.stanford.edu/pages/viewpage.action?pageId=136365158#AutomatedAccessioningandObjectRemediation(pre-assemblyandassembly)-SMPLContent

**Comment by aaron-collier** [comment]
@astridu Can you provide a simple design for the "Update the UI so users can indicate if they are submitting a manifest"? 

If you need any pre-assembly info, please check with @andrewjbtw.

**Comment by astridu** [comment]
@aaron-collier 
Add a checkbox labeled "I have a file manifest" under the content metadata creation dropdown.
![image](https://user-images.githubusercontent.com/42216982/112231125-52f47b80-8bf3-11eb-8c86-48480fb13142.png)

**Comment by andrewjbtw** [comment]
I will supply the CSV headers tomorrow to unblock the remaining blocked parts of this issue.

For background the current process with the media_manifest.csv is documented here
https://github.com/sul-dlss/pre-assembly/wiki/Accessioning-complex-content

**Comment by peetucket** [comment]
Notes:

- rename media_manifest.csv everywhere to content_metadata_manifest.csv
- update documentation that refers to media manifests
- uddate class and method names to avoid references to media
- update checks for `media_cm_style` to instead look for new checkbox
- add new checkbox to indicate when you want the manifest instead of just being media projects

**Comment by andrewjbtw** [comment]
@peetucket since we may be going away from the name "content metadata" - cocina is calling it "structural" metadata, and eventually[?] the purl will stop calling it contentMetadata too, I think the manifest should have some other name. I had suggested file_manifest.csv above, but I could see that potentially being confusing by being too generic.

**Comment by peetucket** [comment]
ahh, good point, i missed that suggestion - i think `file_manifest.csv` is fine -- I'll go with that

**Comment by peetucket** [comment]
Note that the current implementation supports an optional column called `thumb` in the file manifest, just to note to add to the list above for documentation.  If you set the value of this column to `true` or `yes` for any file in a resource, it will add a `thumb=yes` attribute to the entire resource.

More documentation here: https://consul.stanford.edu/pages/viewpage.action?pageId=136365158#AutomatedAccessioningandObjectRemediation(pre-assemblyandassembly)-SMPLContent

**Comment by andrewjbtw** [comment]
Huh. I wonder if that "thumb" attribute ever worked. We had a problem earlier this year where "thumb=yes" was added to resources (possibly on the basis of that documentation? it was inserted automatically via mapping) and the result was that they did not display on the purl. So we removed the attribute.

I will check with SMPL, but if that attribute is unused I think we should drop support.

**Comment by peetucket** [comment]
Ok, sounds good.  It is optional, so can be left off the manifest, but better to remove if never needed.  They will need to update their manifests a bit (besides renaming the file to 'file_manifest.csv') to do things like add the `druid` column, but so far my changes are mostly backwards compatible.

**Comment by peetucket** [comment]
This should now be ready for some testing in the PR.  It should function exactly as described in the comments above.  A couple additional notes to add to what was described (for when we do the documentation) ...

Note, a good base for the documentation (presumably added to https://github.com/sul-dlss/pre-assembly/wiki) could be the existing SMPL documentation (https://consul.stanford.edu/pages/viewpage.action?pageId=136365158#AutomatedAccessioningandObjectRemediation(pre-assemblyandassembly)-SMPLContent) ...  after which we will want to clearly mark that Consul page as DEPRECATED. 

1. A **druid** column is now required to specify which object the file belongs to.  The columns MUST be filled in each file in that object (and obviously with the same druid to match the other files in that object).
2. The **sourceid** column referenced in the old SMPL documenation has been removed completely and will be ignored if included.  We should remove references when documenting.  I think it was unused anyway.
3. All of the SMPL specific "roles" (e.g. such as "sl", "sh") that are derived from SMPL filename conventions and used to drive specific publish/preserve/shelve still work in the current PR, but I think we should get rid of them and just require the publish/preserve/shelve columns to be set for each specific file.  If we leave the SMPL specific filename convention stuff in there, it can cause problems if a non media project happens to have the specific filename pattern (e.g. "_sl") in a filename, as it might interfere with the publish/preserve/shelve settings.   If we ditch all of the special filename stuff, SMPL will just have tp specify which exact publish/preserve/shelve attributes they want for each file instead of getting some defaults based on filename, which is going to be required for all other projects that use the new manifest anyway.  I think it makes sense to just be consistent and not presume specific SMPL filename patterns.
4.  (assuming it's not removed) - the manifest can optionally include an additional column called **thumb**    If a thumb column is included, and you put "yes" or "true" in that column for any file in a given resource/sequence, that resource will be marked with the "thumb=yes" attribute.  It doesn't matter which file in that selected sequence gets the value in the thumb column, but you should be sure to set that column blank for any sequences that are not thumbs.

**Comment by ndushay** [comment]
Peter - is this now ready for Andrew to sign off by doing testing?
