### ISSUE TITLE
analyze where discovery reports (and preassembly runs?) spend the most elapsed time.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/pre-assembly#908]
Use case:

Mary Ellen does discovery reports for content in very large batches from a Newspaper collection that is being digitized.  These batches take days to run, and have taken up to 5 days as far as Andrew has noticed.  See Andrew's comment below for more information.

**Comment by jcoyne** [comment]
How big is a very large batch?  How fast do we need it to be before we can claim this is done?

**Comment by andrewjbtw** [comment]
In my thinking, which is driven by an existing pain point, this is related more to discovery reports than to preassembly jobs. I'm not sure if improving the speed for one job type would necessarily improve the speed for the other.

The specific problem with discovery reports is this: when you have a job that contains tens or hundreds of thousands of files, the discovery report can take hours or days to complete. From memory, the longest I've ever seen a discovery report run was in the range of 5-6 days. It might be worth checking the timestamps of past jobs to determine what's been the longest run, if we have the data. I would expect to see a close relationship between number of files and report job duration. The size of the files seems less important.

There are multiple problems with discovery reports that take this long:

- The amount of time is itself a problem once you start to get into the multi-day range
- The longer a report runs, the greater the risk it's interrupted -- and there's no clear "correct" way to resume (resque? use the web GUI?). The size of the job doesn't seem to cause a failure, failures on long-running jobs tend to come from network disconnects or Preassembly app redeploys.
- An interrupted report does not save progress. If it runs for 3 days and fails, it will take 3 more days after resumption to reach the same point. There have been cases where I or other users have split a big job into multiple jobs after giving up on the big job succeeding. 

The questions I have, before coming up with a metric for how fast would be fast enough:

- What parts of the discovery report and preassembly jobs take longest now?
- Of the steps that consume the most time, what potential is there to increase the speed?

Beyond speed improvements, being able to resume a discovery report without starting over would be a huge improvement. Preassembly jobs save progress in a log that allows them to pick up where they left off, so long-running jobs are less of a problem because you can keep resuming them until they finish the batch.

**Comment by ndushay** [comment]
- Can we parallel-ize?

**Comment by ndushay** [comment]
Questions
- did the removal of Fedora improve this?
- does the discovery report do checksums?  (this can be very slow for large files, and would also matter for lots of files) - Naomi is actively researching this

@andrewjbtw - can you provide exemplar data for this, if it is still a problem?   (because it is a discovery report only, can it be run on prod for timings?)

**Comment by ndushay** [comment]
Are checksums computed for discovery reports?

### when using file_manifest approach
- no?

### when not using file_manifest approach
- no?
- yes, when it's a pre-assembly RUN (not discovery report), and it is computed by assembly-objectfile gem (calls to `Assembly::ContentMetadata.create_content_metadata`)

**Comment by ndushay** [comment]
Actions for this ticket:

- do some analysis from logs, or do some benchmarking to determine which parts of the discovery report and preassembly jobs take longest.

- of the steps that consume the most time, what potential is there to increase the speed?  Discuss with team, and doing THAT work can be expressed as separate tickets.

**Comment by jmartin-sul** [comment]
attaching a spreadsheet i created monday with the data from a memory profiling run this past friday (using [this commit](https://github.com/sul-dlss/pre-assembly/commit/2bc0a2d3b0dc9f69adee2549ae7001e18e2a38bd)).  the first tab is filtered to just the pre-assembly application code, the second is all of the memory profiling output (including for gems and stdlib).

a few notes:
* keeping an eye on things in `htop`, i saw the discovery report worker for this test batch from @andrewjbtw consume at least 7.8 GB of memory (it seemed to keep growing without decrease -- i didn't see what it maxed out on at the very end).  andrew noticed similar behavior in his testing.
* it seems like the profiling report tracks cumulative memory allocation for the duration of the job run, and so it's a bit hard to tell solely from the report whether something is a memory hog in the sense of holding onto a lot in memory all at once, vs just allocating (but also releasing) a lot of memory over the course of the run.
* the code i'm immediately most suspicious of, when considering likely behavior against the memory report, is `Batch#digital_objects`.  it appears to hold an array of all `DigitalObject`s for the report in memory, and it consumed about 7.5 GB of memory, which is not that far under the max memory usage i observed for the worker process in htop.
* annoying gotcha: ruby-prof seems to crash sometimes when writing out its reports, but it did seem to at least output the flat report that i used to generate the attached spreadsheet (i'd hoped to get callgrind output that i could use for more nuanced visualization in qcachegrind, but the `tree`/`CallTree` report failed to write, it seems).

New Relic didn't pan out: we are unable to provision new seat licenses at present, and some combination of the limited insight given by the free plan and New Relic not playing well with Resque processes left it unable to give us useful profiling info here (New Relic's admin UI complained that it can't do fine-grained stack trace sampling profiling on Resque worker processes, though the marketing copy claims New Relic is useful for comparing Sidekiq vs Resque vs DelayedJob).

Will also attach CPU profiling info from pointing [rbspy](https://rbspy.github.io/) at the `DiscoveryReportJob` process while running the above described test.

see also this ticket for fixing the memory usage issue:  https://github.com/sul-dlss/pre-assembly/issues/961

**Comment by jmartin-sul** [comment]
[`rbspy`](https://rbspy.github.io/) output for the above described profiling run, filtered for just our app code (`grep "/opt/app/preassembly/pre-assembly/releases/" /opt/app/preassembly/.cache/rbspy/2022-06-04-HR7eL1YqAa.summary_by_line.txt`):  
[pre-assembly_908_rbspy-2022-06-04-HR7eL1YqAa.summary_by_line.filter-to-app-code.txt](https://github.com/sul-dlss/pre-assembly/files/8864297/pre-assembly_908_rbspy-2022-06-04-HR7eL1YqAa.summary_by_line.filter-to-app-code.txt)

full `rbspy` output for that profiling run: 
[pre-assembly_908_rbspy_2022-06-04-HR7eL1YqAa.summary_by_line.txt](https://github.com/sul-dlss/pre-assembly/files/8864305/pre-assembly_908_rbspy_2022-06-04-HR7eL1YqAa.summary_by_line.txt)

also rbspy is awesome: point it at a running process, get useful CPU profiling info.  and it's a sampling profiler with an easily settable sampling rate, so could be used in production if need be (this testing was all done in stage).

i suspect the more serious problem here is memory consumption, but it was easy enough to get CPU profiling info with rbspy that it felt like i might as well include it.

**Comment by jmartin-sul** [comment]
"self" time in the rbspy output is time spent in the method itself.  "total" time is the total time spent in the method, including time spent waiting for child calls from that method to return.  note that `ObjectFileValidator#validate` consumed 20.84% of total CPU time for the job, and `Batch#digital_objects` took 8.9%.  the other big consumers of total CPU time in our code were the top level things you'd expect: e.g. `DiscoveryReportJob#perform`.

**Comment by andrewjbtw** [comment]
For reference, the discovery report I was running where the job uses a file_manifest.csv is here: https://sul-preassembly-stage.stanford.edu/job_runs/1719

It runs for about 40 minutes and consumes somewhere around 5 GB of memory by the end. I was initially just trying to make a job that would run for 90 minutes, similar to what @jmartin-sul was testing (which doesn't use a file manifest), but I found it either took 30-40 minutes or it never finished at all. I started incrementally adding 10-15 druids at a time and watching `htop` while it run, which is how I noticed the memory usage.

It doesn't seem necessary at this point, but I could keep adding more druids to get a longer running time. The file manifest job has fewer total druids and fewer files than the batch that John is testing, but seems to get close to the same memory footprint.

**Comment by andrewjbtw** [comment]
I had a script run `free -m` every minute while my file manifest test was running. This was the output right before the job completed:
```
              total        used        free      shared  buff/cache   available
Mem:           5804        5582         115          15         106          34
Swap:          2047        1027        1020
```

**Comment by jmartin-sul** [comment]
> John / Andrew: do you think we should spend effort looking into `ObjectFileValidator#validate` or hold off until we do ticket #961 ?

i could go either way -- i'd probably do #961 first, since my gut feeling is that it's probably allocating a bunch of memory that it doesn't release till the job finishes.  `ObjectFileValidator#validate` is probably what i'd look to next, if 961 doesn't pan out.  might be possible to work on the two places in parallel, if we wanted a couple people working on this at the same time?  not sure how conflict-y that might get if changes resulted from both efforts.

**Comment by jmartin-sul** [comment]
did one last memory profiling run using this commit:  https://github.com/sul-dlss/pre-assembly/commit/4b749e1452337cb58e2f23da23497f99f7b39996

that specific commit re-enables profiling, but the couple commits before it make some tweaks to the way `Batch` and `DiscoveryReport` instantiate and iterate over objects, and testing seemed to indicate that these changes made a significant difference in report running.  in particular, i think i was able to successfully execute [a clone](https://sul-preassembly-stage.stanford.edu/job_runs/1744) of a file manifest based discovery report.  previously, that report would ballooon to 6+ GB of memory usage before being killed between the 60 and 120 minute mark.  the memory usage tweaks are being shaped up into a real PR [here](https://github.com/sul-dlss/pre-assembly/pull/965).  with the changes, the report completed in just under an hour on each of two test runs, and never seemed to get past 900 MB of memory usage at any one time.

updated the above linked spreadsheet with results from today's memory profiling run (using a clone of the same `batch-o-stuff` discovery report i'd first tested with, for better comparability; that report doesn't use a file manifest, fwiw):  
[pre-assembly 908 - discovery report memory usage profile (ruby-prof).xlsx](https://github.com/sul-dlss/pre-assembly/files/8904596/pre-assembly.908.-.discovery.report.memory.usage.profile.ruby-prof.xlsx)

from looking at the profiling output, you can still see methods like `Batch#digital_objects` cumulatively allocating around 14 GB of memory, and you can see `DiscoveryReport#process_dobj` allocating 6+ GB, and `ObjectFileValidator#validate` allocating 6+ GB, and `DiscoveryReport#to_builder` allocating 14+ GB.  but if you watch the resque process in `htop`, you never see it get past the 800 MB range for memory usage at any one time.  so it'd seem like memory is being freed appropriately (and the same seems to be true of batches that do have a file manifest, unlike this test, based on last night's testing with `full_file_manifest_test_Set`, which do use a file manifest)

**Comment by ndushay** [comment]
Let's leave it open for a bit;  I'll put it into the backlog to clean up the board a bit.

**Comment by ndushay** [comment]
marked blocked until we know if PR #965 is sufficient
